-- SPDX-License-Identifier: AGPL-3.0-or-later
-- SPDX-FileCopyrightText: 2025 Jonathan D.A. Jewell
--
-- CivicConnect Verification Module
-- Decentralized event verification using ed25519 signatures
--
-- Security: This module handles cryptographic verification
-- Signatures are generated by organizers and verified by attendees
-- No central approval authority required
--
-- Anti-gaming measures:
-- - Rate limiting: Max 3 verifications per day per user
-- - Temporal validation: Within event time window only
-- - Spatial validation: Within coarse geofence
-- - Fraud detection: Pattern analysis for suspicious activity

with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Ada.Calendar;

package Civicconnect.Verification is

   --  Rate limiting constants
   Max_Verifications_Per_Day : constant := 3;
   Verification_Window_Minutes : constant := 30;  -- Before/after event time

   --  Verification statuses
   type Verification_Status is
     (Pending,
      Verified,
      Rejected_Invalid_Signature,
      Rejected_Outside_Time_Window,
      Rejected_Outside_Location,
      Rejected_Rate_Limited,
      Rejected_Already_Verified,
      Rejected_Fraud_Detected);

   --  QR code payload structure
   --  Contains: event_id, organizer_id, timestamp, nonce
   --  Signed with organizer's ed25519 private key
   type QR_Payload is record
      Event_ID       : Event_ID;
      Organizer_ID   : User_ID;
      Timestamp      : Ada.Calendar.Time;
      Nonce          : Unbounded_String;  -- Random 32 bytes, hex encoded
      Signature      : Unbounded_String;  -- ed25519 signature, hex encoded
   end record;

   --  Verification record for audit log
   type Verification_Record is record
      ID             : Positive;
      Event_ID       : Event_ID;
      User_ID        : User_ID;
      Organizer_ID   : User_ID;
      Status         : Verification_Status;
      Signature      : Unbounded_String;
      Verified_At    : Ada.Calendar.Time;
      XP_Awarded     : Experience_Points;
      Location_Hash  : Unbounded_String;  -- H3 cell at verification time
   end record;

   --  Generate QR payload for event organizer
   --  Called by organizer to create scannable verification code
   function Generate_QR_Payload
     (Event        : Event_ID;
      Organizer    : User_ID;
      Private_Key  : String) return QR_Payload;

   --  Verify QR payload scanned by attendee
   --  Returns verification status and awards XP on success
   function Verify_Attendance
     (Payload      : QR_Payload;
      Attendee     : User_ID;
      Public_Key   : String;
      Location     : String;  -- H3 cell ID
      Current_Time : Ada.Calendar.Time) return Verification_Status;

   --  Check if user has already verified for this event
   function Already_Verified
     (Event : Event_ID;
      User  : User_ID) return Boolean;

   --  Check if user has exceeded daily verification limit
   function Is_Rate_Limited (User : User_ID) return Boolean;

   --  Check if verification is within event time window
   function Is_Within_Time_Window
     (Event_Start  : Ada.Calendar.Time;
      Event_End    : Ada.Calendar.Time;
      Current_Time : Ada.Calendar.Time) return Boolean;

   --  Record verification in audit log (append-only)
   function Record_Verification
     (Verification : Verification_Record) return Operation_Result;

   --  Get verification history for user (for fraud detection)
   function Get_User_Verifications
     (User        : User_ID;
      Since_Days  : Natural := 30) return Natural;

private

   --  Signature validation via Rust FFI
   function Validate_Signature
     (Payload    : QR_Payload;
      Public_Key : String) return Boolean;

   --  Fraud detection heuristics
   function Check_Fraud_Patterns
     (User     : User_ID;
      Event    : Event_ID;
      Location : String) return Boolean;

end Civicconnect.Verification;
