# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 Jonathan D.A. Jewell
#
# CivicConnect Development Environment
# Uses Podman (NOT Docker) for rootless containers
#
# Usage:
#   podman-compose up -d
#   podman-compose down
#   podman-compose logs -f

version: "3.9"

services:
  # PostgreSQL with PostGIS extension
  postgres:
    image: docker.io/postgis/postgis:15-3.4-alpine
    container_name: civicconnect-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: civicconnect
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-civicconnect_dev}
      POSTGRES_DB: civicconnect_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U civicconnect -d civicconnect_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and sessions
  redis:
    image: docker.io/redis:7-alpine
    container_name: civicconnect-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO for S3-compatible object storage
  minio:
    image: docker.io/minio/minio:latest
    container_name: civicconnect-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-civicconnect}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-civicconnect_dev}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  default:
    name: civicconnect-network
